### ISSUE TITLE
Help with uploading code using the Arduino IDE

### ISSUE THREAD

**Issue by kumarpatel** [Incuvers-Inc/Model-1#38]
Cc. @timsp , Flemming Rasmussen <fgrazz@ns.sympatico.ca>
_______________________________________________________________________________________
Update: 24th December

Successfully compiled and uploaded code (without making any changes to master branch) to Model-1
I had to change Board type in Arduino IDE to **Arduino/Genuino Mega or Mega 2560**
and Processor to **ATmega2560 (mega 2560)**

Now my question is what is the significance of the below .ino files.
[Incuvers_Incubator.ino](https://github.com/Incuvers-Inc/Model-1/blob/master/Arduino%20Sketches/Main/Incuvers_Incubator/Incuvers_Incubator.ino)
[IncuversHardwareDefinitionWriter.ino](https://github.com/Incuvers-Inc/Model-1/blob/master/Arduino%20Sketches/Support/IncuversHardwareDefinitionWriter/IncuversHardwareDefinitionWriter.ino)

Could you point me to a piece of documentation that might explain this?
_______________________________________________________________________________________

23rd December

I've been following this guide.
https://github.com/Incuvers-Inc/Model-1/wiki/Uploading-code-using-the-Arduino-IDE

Installed all three libraries.
MAX31850 DallasTemp by Adafruit" -> 1.0.0
MAX31850 OneWire by Adafruit" -> 1.0.1
arduino-display-lcdkeypad -> 4.0.2 (removed LcdKeypad.h and LcdKeypad.cpp)

Programmer: AVRISP mkII
Board: Arduino/Genuino UNO

Open *Arduino Sketches/Main/Incuvers_Incubator/Incuvers_Incubator.ino* in Arduino IDE.
(Side note: There's also Arduino Sketches/Support/IncuversHardwareDefinitionWriter/IncuversHardwareDefinitionWriter.ino)
Not sure which ino file is meant to be compiled as part of the above documentation

Then upon compiling, I get the following error:
```
In file included from /Users/kumarpatel/Projects/Model-1/Arduino Sketches/Main/Incuvers_Incubator/Incuvers_Incubator.ino:113:0:
sketch/SenseWrap_Serial.h: In member function 'void IncuversSerialSensor::Initialize(int, int, String, String)':
SenseWrap_Serial.h:19:23: error: 'Serial3' was not declared in this scope
           this->dC = &Serial3;
                       ^~~~~~~
sketch/SenseWrap_Serial.h:19:23: note: suggested alternative: 'Serial'
           this->dC = &Serial3;
                       ^~~~~~~
                       Serial
SenseWrap_Serial.h:25:23: error: 'Serial2' was not declared in this scope
           this->dC = &Serial2;
                       ^~~~~~~
sketch/SenseWrap_Serial.h:25:23: note: suggested alternative: 'Serial'
           this->dC = &Serial2;
                       ^~~~~~~
                       Serial
SenseWrap_Serial.h:31:23: error: 'Serial1' was not declared in this scope
           this->dC = &Serial1;
                       ^~~~~~~
sketch/SenseWrap_Serial.h:31:23: note: suggested alternative: 'Serial'
           this->dC = &Serial1;
                       ^~~~~~~
                       Serial
Multiple libraries were found for "LiquidTWI2.h"
 Used: /Users/kumarpatel/Documents/Arduino/libraries/arduino-display-lcdkeypad
Multiple libraries were found for "EEPROM.h"
 Used: /private/var/folders/df/92xjf87j399f425k10qc_dfxns4bp5/T/AppTranslocation/5C351A8F-4092-4A00-BA3D-0090CDF42CC4/d/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM
Multiple libraries were found for "OneWire.h"
 Used: /Users/kumarpatel/Documents/Arduino/libraries/MAX31850_OneWire
Multiple libraries were found for "DallasTemperature.h"
 Used: /Users/kumarpatel/Documents/Arduino/libraries/MAX31850_DallasTemp
Multiple libraries were found for "Wire.h"
 Used: /private/var/folders/df/92xjf87j399f425k10qc_dfxns4bp5/T/AppTranslocation/5C351A8F-4092-4A00-BA3D-0090CDF42CC4/d/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire
exit status 1
'Serial3' was not declared in this scope
```

**Comment by davidsean** [comment]
Hi @kumarpatel, if your board supports it, try using the develop branch. It will soon be merged in master.

If you have an older board you will need run first

`IncuversHardwareDefinitionWriter.ino`. It is used to define the temperature probes. One for the door one for the chamber. This is only needed to be once. The probe IDs are saved to the board (EEPROM) afterwards. This step should have been performed before you received the incubator.

`Incuvers_Incubator.ino` is the main file, you want to upload this to get your incubator working.

**Comment by davidsean** [comment]
Hi @kumarpatel, 

Thanks, I have updated the wiki about Board and Processor.
Since you can now upload the code I will close the issue, feel free to re-open .
